import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Header from '../components/header'
import Footer from '../components/footer'
// import MyApp from './_app/page' 
import GlobalState from '@/context'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Headless Blog',
  description: 'Generated by create next app',
}



const RootLayout=({children}: {
  children: React.ReactNode
})=> 
  (
    <html lang="en">      
        
      <body className={inter.className}>
            {/* <GlobalState> */}
              <Header/>
              <main>{children}</main>
              <Footer/>
            {/* </GlobalState> */}
        </body>
    </html>
  );

export default RootLayout;  




// function MyApp({Component,pageProps}){
//   <Head>
//     <meta name="viewport" content="width=device-width, height=device-height, initial-scale=1.0, maximum-scale=1.0"/>
//   </Head>
//   useEffect(() => {
//     console.log("I am useeffect from app.js")
//   }, [])

//   const [cart, setCart] = useState([])
//   const [reloadKey, setReloadKey] = useState(1)
 
//   const addToCart = (item, qty, price) => {
//     console.log("Add to cart")
//     let newCart = cart
//     for (let index = 0; index < qty; index++) {
      
//       newCart.push([item, price])
//     }
//     console.log("Add to cart", newCart)
//     setCart(newCart)
//     setReloadKey(Math.random())
//   }

//   const removeFromCart = (item, qty) => {
//     let newCart = cart
    
//     let index = newCart.indexOf(item)
//     newCart.splice(index)
//     setCart(newCart)
//   }

//   const clearCart = (item) => {
//     setCart([])
//   }

//   return( 
//   <>
//     <Header key={reloadKey} cart={cart} />
//       <Component cart={cart} removeFromCart={removeFromCart} addToCart={addToCart} clearCart={clearCart} {...pageProps} />
//     <Footer/>
//   </>
  
//   )
//   }

// export default MyApp
