import 'bootstrap/dist/css/bootstrap.css';
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import BootstrapClient from '@/components/bootstrapclient'
import './globals.css'
import { Suspense } from 'react';
import Footer from '@/components/footer';
import Header from '@/components/header';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Headless Blog',
  description: 'Generated by create next app',
}

const RootLayout=({children}: {
  children: React.ReactNode
})=> 
  (
    <html lang="en">      
        
      <body className={inter.className}>
      
        
        <Header/>
            <Suspense>
            {children}
            </Suspense>
            <BootstrapClient/>
            <Footer />
        </body>
    </html>
  );

export default RootLayout;  